version: '3.6'
services:
  node:
    container_name: "bt_node"
    image: "node:8-stretch"
    user: "node"
    ports: [ "${NODE_PORT}:${NODE_PORT}" ]
    env_file:
      - .env
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    depends_on:
      - mongodb
    command: "npm run dev"

  mongodb:
     container_name: "bt_mongodb"
     image: "mongo"
     ports: [ "${MONGO_PORT}:${MONGO_PORT}" ]
     env_file:
       - .env
     restart: always
     volumes:
       - mongodb_data:/data/db

volumes:
  mongodb_data: